### ISSUE TITLE
Assembly available not retrieved by GCsnap

### ISSUE THREAD

**Issue by mariaartlle** [JoanaMPereira/GCsnap#2]
Hello,
I'm trying to use GCsnap for comparing the genomic context of different species but I'm having a problem with the assembly retrieval for some UniprotIDs. I have tried to run GCsnap with these proteins (P03023, P0ACT4, Q47RE1, Q9AL35, Q2YIQ4, S4S3A4) but the program is not able to find their assembly:

![image](https://user-images.githubusercontent.com/82810298/201900957-8de1e594-a262-4c6e-800a-aed425ec9ee1.png)

I have manually checked in the Uniprot entries of all the proteins and they all have an available assembly linked but GCsnap apparently is not able to retrieve them. Is there any chance that this is a known error or that currently there is a problem with the ncbi id mapper? 

Thank you very much!

**Comment by JoanaMPereira** [comment]
Hi Maria! Thanks for using GCsnap and reporting this issue :)

Two weeks ago I ran into the same issue and realised there was a change on the way one has to query GenBank using an API. I fixed that about 2 weeks ago. When did you last update GCsnap? You can try and pull it again. Hopefully you are facing the same issue. If it still does not work, then I will have to look deeper into the issue.

I hope this helps!

Best wishes
Joana

**Comment by mariaartlle** [comment]
Hi Joana, 
I installed GCsnap yesterday and executed it today after doing a pull from the master branch. I've tried to pull and execute it again but the output is the same...

**Comment by JoanaMPereira** [comment]
Hi Marie,
Thanks for confirming!

I had a look at the issue and found the problem. As default, when mapping UniProtIDs to GenBank, GCsnap was first mapping to EMBL/GenBank CDS instead of RefSeq, which was taking the search on the wrong direction. That is fixed now, and it works for your sequences now. 

However, I noticed that these inputs are very diverse and there is no conserved genomic context between them. Of course it depends on your ultimate goal, but I wanted to highlight that GCsnap is more adequate to compare the genomic contexts of homologous proteins/genes, or genes that are expected to be in a conserved genomic context. But of course, you are free to use it as you want :)

Best wishes and good luck!

J

**Comment by mariaartlle** [comment]
Hi Joana, 
Thank you very much for your help! Yes, they are very different indeed, I'll keep in mind your recommendations for using GCsnap in the future. I find GCsnap very useful and easy to use, congratulations on your work! 

Best wishes, 
Maria

**Comment by raulmireles** [comment]
Hi Joana, this issue is showed again. I even tried to run the example file (targets_ybez_selected.txt) and I still get this messages. Any insight regarding this? 

I downloaded GCSnap on 16aug2023.

![Screen Shot 2023-08-16 at 14 50 49](https://github.com/JoanaMPereira/GCsnap/assets/87815405/92a448d7-917d-41f1-b9ca-15acaeced6ea)

**Comment by JoanaMPereira** [comment]
Hi Raul,

Thanks for reporting this. I tried it and unfortunately I couldn’t reproduce the error… maybe it was some problem with connecting to the online databases. Glitches happen and databases may be down. Did you try again some time later?

Best wishes
Joana

On 16 Aug 2023, at 14:20, Raul Mireles ***@***.***> wrote:



Hi Joana, this issue is showed again. I even tried to run the example file (targets_ybez_selected.txt) and I still get this messages. Any insight regarding this?

I downloaded GCSnap on 16aug2023.

[Screen Shot 2023-08-16 at 14 50 49]<https://user-images.githubusercontent.com/87815405/260998733-92a448d7-917d-41f1-b9ca-15acaeced6ea.png>
